### ISSUE TITLE
关于光标的问题

### ISSUE THREAD

**Issue by QinZhen001** [mouday/more-editor#1]
最近在研究编辑器发现了两个问题：

1.当点击编辑器外部区域，让后在点击@按钮，@文本会错位
应该是selection.getRangeAt(0) 拿到的位置不对导致的
![](https://s1.ax1x.com/2023/03/10/ppuWawR.jpg)

2.点击@按钮后，光标往前移动一位，再次点击@按钮，node插入位置为span中间，导致鼠标无法顺畅左右移动了
![](https://s1.ax1x.com/2023/03/10/ppuWdT1.jpg)

**Comment by mouday** [comment]
最近看到一篇基于Vue的文章，看有没有什么提示

[Vue: 评论区实现发表情和@某人消息推送](https://juejin.cn/post/7200689071261106233)

**Comment by QinZhen001** [comment]
> Owner

十分感谢

文章中 "\u200B" 的做法比空span要好些，这样@插入的问题就解决了。
键盘左右移动的问题，由于存在 "\u200B" 确实是需要两次 <-  <-，keydown 事件event也没法破，要解决这个细节问题的话估计要手写光标了 Orz

**Comment by QinZhen001** [comment]
十分感谢。
文章中"\u200B"代替空的span的做法体验上会好很多，@插入位置的问题就解决了。
由于存在"\u200B"，键盘左键移动时，还是需要点击两次 <- <-，keydown事件方案没法破，要解决这个的话估计得手写光标了 Orz
